/**
 * Shared analytics scope and capability contracts (Phase 2, Step 2.1).
 *
 * Client-safe pure TypeScript only: no React, no Supabase, no server-only
 * imports. Later steps build on these contracts — Step 2.2 adds filters and
 * URL state, Step 2.3 adds metric/sample/eligibility results, Step 2.4 adds
 * approved calculations, and Step 2.5 adds repository queries. See
 * `docs/redesign/ANALYTICS-SCOPE-CAPABILITY-MODEL.md` for the usage guide.
 */

export {
  ANALYTICS_SCORE_SOURCE_KEYS,
  ANALYTICS_SUBJECT_ISSUE_CODES,
  ANALYTICS_SUBJECT_KINDS,
  analyticsSubjectKey,
  analyticsSubjectRefsEqual,
  isAnalyticsScoreSourceKey,
  isAnalyticsSubjectKind,
  validateAnalyticsSubjectRef,
  type AnalyticsScoreSourceKey,
  type AnalyticsSubjectDisplay,
  type AnalyticsSubjectIssue,
  type AnalyticsSubjectIssueCode,
  type AnalyticsSubjectKind,
  type AnalyticsSubjectRef,
  type AwardSubjectRef,
  type CardSubjectRef,
  type CorporationPreludePairingSubjectRef,
  type CorporationSubjectRef,
  type GameSubjectRef,
  type GroupSubjectRef,
  type LabeledAnalyticsSubject,
  type MapSubjectRef,
  type MilestoneSubjectRef,
  type PlayerSubjectRef,
  type PreludeSubjectRef,
  type ScoreSourceSubjectRef,
  type StyleSubjectRef,
  type TagSubjectRef,
} from './subjects';

export {
  ANALYTICS_DOMAIN_KINDS,
  ANALYTICS_POPULATION_KINDS,
  ANALYTICS_SCOPE_ISSUE_CODES,
  ANALYTICS_SCOPE_TYPES,
  describeAnalyticsDatasetContext,
  isAnalyticsDomainKind,
  isAnalyticsScopeType,
  validateAnalyticsScope,
  type AnalyticsDatasetContext,
  type AnalyticsDomainKind,
  type AnalyticsPopulationKind,
  type AnalyticsScope,
  type AnalyticsScopeIssue,
  type AnalyticsScopeIssueCode,
  type AnalyticsScopeType,
  type AnalyticsScopeValidation,
  type ComparisonAnalyticsScope,
  type DomainAnalyticsScope,
  type GameAnalyticsScope,
  type GlobalAnalyticsScope,
  type GroupAnalyticsScope,
  type IndividualAnalyticsScope,
} from './scopes';

export {
  ANALYTICS_COVERAGE_ISSUE_CODES,
  ANALYTICS_COVERAGE_EVALUATION_STATUSES,
  ANALYTICS_COVERAGE_UNKNOWN_REASON_CODES,
  ANALYTICS_COVERAGE_STATUSES,
  analyticsCoverageRatio,
  analyticsCoverageStatus,
  capabilityUnavailableAnalyticsCoverage,
  evaluateAnalyticsCoverage,
  normalizeAnalyticsCoverage,
  unknownAnalyticsCoverage,
  toCoverageObservation,
  validateAnalyticsCoverage,
  type AnalyticsCoverage,
  type AnalyticsCoverageBreakdownEntry,
  type AnalyticsCoverageCounts,
  type AnalyticsCoverageEvaluation,
  type AnalyticsCoverageIssue,
  type AnalyticsCoverageIssueCode,
  type AnalyticsCoverageStatus,
  type AnalyticsCoverageUnknownReason,
  type AnalyticsCoverageUnknownReasonCode,
  type AnalyticsSourceCoverage,
  type MeasuredAnalyticsCoverageEvaluation,
} from './coverage';

export {
  ANALYTICS_EVIDENCE_ISSUE_CODES,
  ANALYTICS_EVIDENCE_SOURCE_KINDS,
  isAnalyticsEvidenceSourceKind,
  validateAnalyticsEvidence,
  type AnalyticsCalculationVersion,
  type AnalyticsEvidence,
  type AnalyticsEvidenceIssue,
  type AnalyticsEvidenceIssueCode,
  type AnalyticsEvidenceSource,
  type AnalyticsEvidenceSourceKind,
  type AnalyticsEvidenceVerification,
} from './evidence';

export {
  ANALYTICS_CAPABILITY_ISSUE_CODES,
  ANALYTICS_CAPABILITY_REASON_CODES,
  ANALYTICS_CAPABILITY_STATUSES,
  describeAnalyticsCapabilityStatus,
  describeUnsupportedScope,
  isAnalyticsCapabilityExecutable,
  isAnalyticsCapabilityReasonCode,
  isAnalyticsCapabilityStatus,
  isScopeSupportedByCapability,
  validateAnalyticsCapabilityResult,
  type AnalyticsCapabilityIssue,
  type AnalyticsCapabilityIssueCode,
  type AnalyticsCapabilityReason,
  type AnalyticsCapabilityReasonCode,
  type AnalyticsCapabilityRemediation,
  type AnalyticsCapabilityResult,
  type AnalyticsCapabilityStatus,
  type AnalyticsDataRequirement,
  type AnalyticsScopeSupportDeclaration,
  type AnalyticsUnsupportedScopeDeclaration,
  type InsufficientEvidenceAnalyticsCapability,
  type NonExecutableAnalyticsCapability,
  type PartiallySupportedAnalyticsCapability,
  type RequiresNewFieldsAnalyticsCapability,
  type RequiresQueryWorkAnalyticsCapability,
  type RequiresViewAnalyticsCapability,
  type SupportedAnalyticsCapability,
  type UnavailableAnalyticsCapability,
} from './capabilities';

export {
  DECLARED_ANALYTICS_CAPABILITIES,
  DECLARED_ANALYTICS_CAPABILITY_KEYS,
  getDeclaredAnalyticsCapability,
} from './capability-declarations';

export {
  capabilityUnavailableAnalyticsValue,
  isCapabilityUnavailableAnalyticsValue,
  isLoadErrorAnalyticsValue,
  isReadyAnalyticsValue,
  loadErrorAnalyticsValue,
  readyAnalyticsValue,
  type AnalyticsLoadError,
  type AnalyticsResultWarning,
  type AnalyticsValueResult,
  type CapabilityUnavailableAnalyticsValue,
  type LoadErrorAnalyticsValue,
  type ReadyAnalyticsValue,
} from './value-availability';

export {
  ANALYTICS_FILTER_COMPATIBILITY_STATUSES,
  ANALYTICS_FILTER_KEYS,
  ANALYTICS_FILTER_QUERY_PARAMETER_ORDER,
  ANALYTICS_FILTER_REGISTRY,
  ANALYTICS_GAME_STATUSES,
  ANALYTICS_IDENTITY_RESOLUTION_STATUSES,
  ANALYTICS_QUERY_PARAMETER_ORDER,
  ANALYTICS_SELECTION_QUERY_PARAMETER_ORDER,
  createDefaultAnalyticsFilterState,
  createDefaultAnalyticsUrlAddressableState,
  createEmptyAnalyticsSelectionState,
  getAnalyticsFilterDefinition,
  getAnalyticsFilterScopeCompatibility,
  isAnalyticsFilterKey,
  isAnalyticsGameStatus,
  type AnalyticsCanonicalQueryParameter,
  type AnalyticsFilterCardinality,
  type AnalyticsFilterCompatibilityStatus,
  type AnalyticsFilterDefinition,
  type AnalyticsFilterIdentityKind,
  type AnalyticsFilterKey,
  type AnalyticsFilterScopeCompatibility,
  type AnalyticsFilterState,
  type AnalyticsGameStatus,
  type AnalyticsIdentityOwner,
  type AnalyticsIdentityResolution,
  type AnalyticsIdentityResolutionInput,
  type AnalyticsIdentityResolutionStatus,
  type AnalyticsIdentityResolver,
  type AnalyticsNavigationState,
  type AnalyticsSelectionQueryParameter,
  type AnalyticsSelectionState,
  type AnalyticsTransientInteractionState,
  type AnalyticsUrlAddressableState,
  type CorporationPreludeFilterValue,
} from './filters';

export {
  ANALYTICS_FILTER_ISSUE_CODES,
  analyticsSelectionToDashboardSelection,
  canonicalCode,
  canonicalCorporationPreludeFilterValue,
  canonicalIsoDate,
  canonicalNonnegativeInteger,
  canonicalPlayerCount,
  canonicalPositiveInteger,
  canonicalScoreSourceKey,
  canonicalSelectionId,
  canonicalUuid,
  normalizeAnalyticsFilterState,
  normalizeAnalyticsSelectionState,
  reconcileAnalyticsSelectionState,
  serializeCorporationPreludeFilterValue,
  type AnalyticsFilterIssue,
  type AnalyticsFilterIssueCode,
  type AnalyticsFilterNormalizationOptions,
  type AnalyticsFilterNormalizationResult,
  type AnalyticsIdentityState,
  type AnalyticsSelectionAvailability,
  type AnalyticsSelectionDefaults,
  type AnalyticsSelectionNormalizationResult,
} from './filter-normalization';

export {
  ANALYTICS_PROHIBITED_QUERY_PARAMETERS,
  ANALYTICS_URL_INPUT_STATES,
  analyticsSelectionUsesSinglePointField,
  canonicalizeAnalyticsUrlState,
  parseAnalyticsUrlState,
  parseAndNormalizeAnalyticsUrlState,
  partiallyResetAnalyticsUrlState,
  registeredFilterParameterOrderMatchesRegistry,
  resetAnalyticsUrlState,
  serializeAnalyticsSubjectToken,
  serializeAnalyticsUrlState,
  normalizeAnalyticsUrlState,
  type AnalyticsUrlAliasMap,
  type AnalyticsUrlInputState,
  type AnalyticsUrlInputStatus,
  type AnalyticsUrlNormalizationOptions,
  type AnalyticsUrlNormalizationResult,
  type AnalyticsUrlParseResult,
  type AnalyticsUrlResetTarget,
  type AnalyticsUrlSerializationOptions,
  type AnalyticsUrlSerializationResult,
} from './filter-url-state';

export {
  ANALYTICS_ELIGIBILITY_ISSUE_CODES,
  ANALYTICS_ELIGIBILITY_REASON_CODES,
  ANALYTICS_ELIGIBILITY_STATUSES,
  ANALYTICS_GAME_OUTCOME_STATUSES,
  evaluateAnalyticsEligibility,
  validateAnalyticsEligibilityResult,
  type AnalyticsEligibilityEvaluationInput,
  type AnalyticsEligibilityIssue,
  type AnalyticsEligibilityIssueCode,
  type AnalyticsEligibilityReason,
  type AnalyticsEligibilityReasonCode,
  type AnalyticsEligibilityResult,
  type AnalyticsEligibilityStatus,
  type AnalyticsGameOutcomeStatus,
} from './eligibility';

export {
  ANALYTICS_AGGREGATION_KINDS,
  ANALYTICS_METRIC_DEFINITION_ISSUE_CODES,
  ANALYTICS_METRIC_UNIT_KINDS,
  ANALYTICS_METRIC_VALUE_KINDS,
  analyticsMetricKey,
  isRateLikeMetricValueKind,
  validateAnalyticsMetricDefinition,
  type AnalyticsAggregationKind,
  type AnalyticsInterpretationMetadata,
  type AnalyticsMetricCapabilityRequirement,
  type AnalyticsMetricDefinition,
  type AnalyticsMetricDefinitionIssue,
  type AnalyticsMetricDefinitionIssueCode,
  type AnalyticsMetricIdentity,
  type AnalyticsMetricUnit,
  type AnalyticsMetricValueKind,
} from './metric-contracts';

export {
  ANALYTICS_DENOMINATOR_KINDS,
  ANALYTICS_MINIMUM_SAMPLE_POLICY_KINDS,
  ANALYTICS_MINIMUM_SAMPLE_STATUSES,
  ANALYTICS_OBSERVATION_DENOMINATOR_SOURCES,
  ANALYTICS_OBSERVATION_UNIT_KINDS,
  ANALYTICS_SAMPLE_EXCLUSION_STAGES,
  ANALYTICS_SAMPLE_ISSUE_CODES,
  ANALYTICS_SELECTION_SAMPLE_ROLES,
  analyticsObservationUnitKey,
  analyticsSampleBasis,
  buildAnalyticsSampleCounts,
  evaluateAnalyticsMinimumSample,
  normalizeAnalyticsSample,
  validateAnalyticsMinimumSamplePolicy,
  validateAnalyticsSample,
  type AnalyticsDenominator,
  type AnalyticsDenominatorKind,
  type AnalyticsMinimumSampleEvaluation,
  type AnalyticsMinimumSamplePolicy,
  type AnalyticsMinimumSampleReason,
  type AnalyticsMinimumSampleStatus,
  type AnalyticsObservationDenominatorSource,
  type AnalyticsObservationUnit,
  type AnalyticsObservationUnitKind,
  type AnalyticsSample,
  type AnalyticsSampleCounts,
  type AnalyticsSampleDefinition,
  type AnalyticsSampleExclusion,
  type AnalyticsSampleExclusionStage,
  type AnalyticsSampleIssue,
  type AnalyticsSampleIssueCode,
  type AnalyticsSampleSelectionContext,
  type AnalyticsSelectionSampleRole,
  type MetricSpecificAnalyticsObservationUnit,
  type StandardAnalyticsObservationUnit,
} from './sample';

export {
  ANALYTICS_METRIC_INSUFFICIENT_EVIDENCE_REASON_CODES,
  ANALYTICS_METRIC_RESULT_ISSUE_CODES,
  ANALYTICS_METRIC_RESULT_STATUSES,
  capabilityUnavailableAnalyticsMetricResult,
  createReadyAnalyticsMetricResult,
  isCapabilityUnavailableAnalyticsMetricResult,
  isLoadErrorAnalyticsMetricResult,
  isReadyAnalyticsMetricResult,
  validateAnalyticsMetricResult,
  type AnalyticsMetricInsufficientEvidenceReason,
  type AnalyticsMetricInsufficientEvidenceReasonCode,
  type AnalyticsMetricQueryMetadata,
  type AnalyticsMetricResult,
  type AnalyticsMetricResultBase,
  type AnalyticsMetricResultIssue,
  type AnalyticsMetricResultIssueCode,
  type AnalyticsMetricResultStatus,
  type CapabilityUnavailableAnalyticsMetricResult,
  type InsufficientEvidenceAnalyticsMetricResult,
  type LoadErrorAnalyticsMetricResult,
  type LoadingAnalyticsMetricResult,
  type ReadyAnalyticsMetricResult,
} from './metric-result';

export {
  CANONICAL_ANALYTICS_DEFINITIONS,
  CANONICAL_ANALYTICS_FORMULA_VERSION,
  CANONICAL_RATE_AGGREGATION_CODES,
  CARD_ACQUISITION_RATE_FORMULA_CODES,
  canonicalAnalyticsCalculationVersion,
  getCanonicalAnalyticsDefinition,
  getCanonicalCardAcquisitionRateDefinition,
  validateCanonicalAnalyticsDefinitions,
  type CanonicalAnalyticsFormula,
  type CanonicalAnalyticsMetricDefinition,
  type CanonicalRateAggregationCode,
  type CardAcquisitionRateFormulaCode,
} from './canonical-definitions';

export {
  aggregateEndHandCarryover,
  aggregateHandUtilization,
  aggregatePurchaseConversion,
  aggregatePurchasedHandShare,
  calculateEndHandCarryover,
  calculateHandUtilization,
  calculatePurchaseConversion,
  calculatePurchasedHandShare,
  calculateWinPointDifferential,
  type CardAcquisitionRateAggregate,
  type CardAcquisitionRateAggregateInput,
  type CardAcquisitionRateEvaluation,
  type CardAcquisitionRateInput,
  type EndHandCarryoverInput,
  type HandUtilizationInput,
  type PurchaseConversionInput,
  type PurchasedHandShareInput,
  type WinPointDifferentialEvaluation,
  type WinPointDifferentialInput,
} from './calculations';

export {
  ANALYTICS_REPOSITORY_ERROR_CATEGORIES,
  ANALYTICS_REPOSITORY_OPERATION_IDS,
  ANALYTICS_REPOSITORY_ORDER_DIRECTIONS,
  ANALYTICS_REPOSITORY_RESULT_STATUSES,
  createAnalyticsRepositoryDataResult,
  createAnalyticsRepositoryError,
  createAnalyticsRepositoryUnavailable,
  getActiveAnalyticsFilterKeys,
  type AnalyticsRepositoryAuthorizationContext,
  type AnalyticsRepositoryData,
  type AnalyticsRepositoryDiagnostic,
  type AnalyticsRepositoryDiagnosticStage,
  type AnalyticsRepositoryError,
  type AnalyticsRepositoryErrorCategory,
  type AnalyticsRepositoryExecutionContext,
  type AnalyticsRepositoryNoPagination,
  type AnalyticsRepositoryOffsetPage,
  type AnalyticsRepositoryOffsetPaginationInput,
  type AnalyticsRepositoryOperationDeclaration,
  type AnalyticsRepositoryOperationId,
  type AnalyticsRepositoryOrdering,
  type AnalyticsRepositoryOrderDirection,
  type AnalyticsRepositoryPagination,
  type AnalyticsRepositoryPaginationInput,
  type AnalyticsRepositoryQueryMetadata,
  type AnalyticsRepositoryResult,
  type AnalyticsRepositoryResultStatus,
  type AnalyticsRepositoryWarning,
  type EmptyAnalyticsRepositoryResult,
  type ErrorAnalyticsRepositoryResult,
  type PartialAnalyticsRepositoryResult,
  type ReadyAnalyticsRepositoryResult,
  type UnavailableAnalyticsRepositoryResult,
} from './repository-contracts';

export {
  FINALIZED_GAME_RESULT_OPERATION_DECLARATIONS,
  FINALIZED_GAME_RESULTS_DEFAULT_PAGE_SIZE,
  FINALIZED_GAME_RESULTS_MAX_MULTI_SELECT_VALUES,
  FINALIZED_GAME_RESULTS_MAX_PAGE_SIZE,
  FINALIZED_GAME_RESULTS_ORDERING,
  FINALIZED_GAME_RESULTS_SUPPORTED_FILTERS,
  FINALIZED_GAME_SOURCE_MISSING_FIELDS,
  buildFinalizedGameResultsCoverage,
  buildFinalizedGameResultsEvidence,
  toWinPointDifferentialInputs,
  type FinalizedGamePlayerSourceRecord,
  type FinalizedGameSourceMissingField,
  type FinalizedGameSourceProvenance,
  type FinalizedGameSourceRecord,
  type WinPointDifferentialInputMapping,
} from './repository-records';
