-- Fixture-to-persistence assertions (audit F-09/H4). Runs after
-- apply-fixtures.sql (generated by build-fixture-payloads.ts) has replayed
-- the captured production-action payloads through the real RPC. Every check
-- reads PERSISTED rows and compares them against harness.fixture_expectations,
-- which carries the values the real pipeline produced.

-- 1) Expansion facts persisted exactly: mechanic states, counts, and the
-- null-final-Venus contract (missing never becomes zero).
do $$
declare bad int;
begin
  select count(*) into bad
  from harness.fixture_expectations e
  join public.game_expansion_facts f on f.game_id = e.game_id
  where f.venus_next_state <> e.venus_state
     or f.colonies_state <> e.colonies_state
     or f.venus_event_count <> e.venus_event_count
     or f.colony_built_count <> e.colony_built_count
     or f.colony_trade_count <> e.colony_trade_count
     or (e.final_venus_is_null and f.final_venus_scale is not null)
     or (not e.final_venus_is_null and f.final_venus_scale is null);
  if bad <> 0 then
    raise exception 'FIXTURE FAIL 1: % expansion-fact rows differ from the pipeline output', bad;
  end if;

  select count(*) into bad
  from harness.fixture_expectations e
  where not exists (
    select 1 from public.game_expansion_facts f where f.game_id = e.game_id
  );
  if bad <> 0 then
    raise exception 'FIXTURE FAIL 1b: % fixtures missing their expansion-fact row', bad;
  end if;
end $$;

-- 2) Original-byte source identity: the persisted first-class columns match
-- the captured evidence, and because the stored text IS the original bytes,
-- the trigger-derived input_sha256 equals the original hash (H6 end to end).
do $$
declare bad int;
begin
  select count(*) into bad
  from harness.fixture_expectations e
  join public.game_log_imports gli on gli.id = e.import_id
  where e.original_sha256 <> 'n/a'
    and (
      gli.original_source_sha256 is distinct from e.original_sha256
      or gli.original_source_byte_length is distinct from e.original_byte_length
      or gli.parser_run_identity is distinct from e.parser_run_identity
      or gli.input_sha256 is distinct from e.original_sha256
      or encode(digest(gli.raw_log_text, 'sha256'), 'hex')
         is distinct from e.original_sha256
    );
  if bad <> 0 then
    raise exception 'FIXTURE FAIL 2: % imports lost original-byte source identity', bad;
  end if;
end $$;

-- 3) Canonical events persisted completely with the split review contract.
do $$
declare r record; n int; nr int; rv int; g int;
begin
  for r in
    select * from harness.fixture_expectations where original_sha256 <> 'n/a'
  loop
    select count(*),
           count(*) filter (where review_state = 'needs_review'),
           count(*) filter (where review_state = 'reviewed'),
           count(*) filter (where placement_format = 'grid')
    into n, nr, rv, g
    from public.game_log_events
    where game_log_import_id = r.import_id;
    if n <> r.total_events or nr <> r.needs_review_events
       or rv <> r.reviewed_events or g <> r.grid_placements then
      raise exception
        'FIXTURE FAIL 3 (%): persisted events %/nr %/rv %/grid % differ from pipeline %/%/%/%',
        r.fixture_key, n, nr, rv, g,
        r.total_events, r.needs_review_events, r.reviewed_events, r.grid_placements;
    end if;
  end loop;
end $$;

-- 4) Run state flipped to complete for every action-driven fixture.
do $$
declare bad int;
begin
  select count(*) into bad
  from harness.fixture_expectations e
  join public.game_log_imports gli on gli.id = e.import_id
  where e.original_sha256 <> 'n/a'
    and gli.confidence_summary #>> '{run,state}' is distinct from 'complete';
  if bad <> 0 then
    raise exception 'FIXTURE FAIL 4: % imports never completed their persistence run', bad;
  end if;
end $$;

-- 5) Venus: attributed raises persist with parameter movement, and World
-- Government movement stays unattributed (no player fabricated).
do $$
declare r record; n int;
begin
  select * into r from harness.fixture_expectations where fixture_key = 'venus_only';
  select count(*) into n
  from public.game_log_events
  where game_log_import_id = r.import_id
    and event_type in ('venus_scale_increased', 'venus_scale_decreased');
  if n <> r.venus_event_count or n < 4 then
    raise exception 'FIXTURE FAIL 5a: venus events persisted % (facts say %)', n, r.venus_event_count;
  end if;

  if not exists (
    select 1 from public.game_log_events
    where game_log_import_id = r.import_id
      and event_type = 'venus_scale_increased'
      and player_id is null
  ) then
    raise exception 'FIXTURE FAIL 5b: World Government venus movement lost its unattributed state';
  end if;

  if not exists (
    select 1 from public.game_log_events
    where game_log_import_id = r.import_id
      and event_type = 'venus_scale_increased'
      and player_id is not null
      and parameter_steps is not null
  ) then
    raise exception 'FIXTURE FAIL 5c: attributed venus movement lost parameter steps';
  end if;
end $$;

-- 6) Colonies: build and trade events persist with canonical colony ids.
do $$
declare r record;
begin
  select * into r from harness.fixture_expectations where fixture_key = 'colonies_only';
  if not exists (
    select 1 from public.game_log_events
    where game_log_import_id = r.import_id
      and event_type = 'colony_built' and colony_id is not null
  ) then
    raise exception 'FIXTURE FAIL 6a: colony build lost its canonical colony id';
  end if;
  if not exists (
    select 1 from public.game_log_events
    where game_log_import_id = r.import_id
      and event_type = 'colony_traded' and colony_id is not null
  ) then
    raise exception 'FIXTURE FAIL 6b: colony trade lost its canonical colony id';
  end if;
end $$;

-- 7) Grid placements: row/position persist beside the converted flat id.
do $$
declare r record; bad int;
begin
  select * into r from harness.fixture_expectations where fixture_key = 'grid_placement';
  select count(*) into bad
  from public.game_log_events
  where game_log_import_id = r.import_id
    and placement_format = 'grid'
    and (
      board_row is null or board_position is null
      or board_space !~ '^[0-9]{2}$'
      or source_space_id !~ '^[1-9]:[1-9]$'
      or raw_actor_text is null
    );
  if bad <> 0 then
    raise exception 'FIXTURE FAIL 7: % grid placements lost coordinates, actor, or flat id', bad;
  end if;
end $$;

-- 8) Off-reserve exception: the verified ocean records its source card and
-- coarse class; attribution stays with the acting player, never ownership.
do $$
declare r record; v record;
begin
  select * into r from harness.fixture_expectations where fixture_key = 'off_reserve_exception';
  select source_entity, tile_type_class, ownership_state, owner_player_id
  into v
  from public.game_log_events
  where game_log_import_id = r.import_id
    and event_type = 'tile_placed' and board_space = '08';
  if v.source_entity is distinct from r.exception_source_card::text then
    raise exception 'FIXTURE FAIL 8a: exception ocean source card is % (expected %)',
      v.source_entity, r.exception_source_card;
  end if;
  if v.tile_type_class is distinct from 'ocean'
     or v.ownership_state is distinct from 'unknown'
     or v.owner_player_id is not null then
    raise exception 'FIXTURE FAIL 8b: exception ocean class/ownership was altered';
  end if;
end $$;

-- 9) Printed aliases: alias resolutions persist as high/not_required and the
-- importer-corrected objective as high/reviewed.
do $$
declare r record; n int;
begin
  select * into r from harness.fixture_expectations where fixture_key = 'printed_alias';
  select count(*) into n
  from public.game_log_events
  where game_log_import_id = r.import_id
    and event_type in ('milestone_claimed', 'award_funded')
    and confidence_level = 'high' and review_state = 'not_required';
  if n <> 3 then
    raise exception 'FIXTURE FAIL 9a: expected 3 alias-resolved objectives, got %', n;
  end if;
  select count(*) into n
  from public.game_log_events
  where game_log_import_id = r.import_id
    and event_type = 'award_funded'
    and confidence_level = 'high' and review_state = 'reviewed'
    and payload ->> 'resolution' = 'corrected';
  if n <> 1 then
    raise exception 'FIXTURE FAIL 9b: expected 1 importer-corrected objective, got %', n;
  end if;
end $$;

-- 10) Unsupported wording: no mechanic event is fabricated; the state is
-- unsupported, never absence.
do $$
declare r record; n int;
begin
  select * into r from harness.fixture_expectations where fixture_key = 'unsupported_pattern';
  select count(*) into n
  from public.game_log_events
  where game_log_import_id = r.import_id
    and (event_type like 'venus_%' or event_type like 'colony_%');
  if n <> 0 then
    raise exception 'FIXTURE FAIL 10: % fabricated mechanic events for unsupported wording', n;
  end if;
end $$;

-- 11) Conflicting evidence: the fact row preserves the conflict; no event or
-- blank child row represents the mechanic, and final Venus stays null.
do $$
declare r record; n int;
begin
  select * into r from harness.fixture_expectations where fixture_key = 'conflicting_evidence';
  if r.venus_state <> 'conflicting_evidence' then
    raise exception 'FIXTURE FAIL 11a: conflicting record lost its state (%)', r.venus_state;
  end if;
  select count(*) into n
  from public.game_log_events gle
  join public.game_log_imports gli on gli.id = gle.game_log_import_id
  where gli.game_id = r.game_id;
  if n <> 0 then
    raise exception 'FIXTURE FAIL 11b: conflicting record has % fabricated event rows', n;
  end if;
end $$;

select 'ALL_FIXTURE_ASSERTIONS_PASSED' as result;
