-- RETIRED / SUPERSEDED — TOMBSTONE. This file is intentionally a no-op.
--
-- It contains no executable statement. Applying it does nothing, and it can
-- never again re-grant `authenticated` EXECUTE on
-- public.resolve_import_guest_identity.
--
-- WHY THIS WAS RETIRED
--
-- This migration was prepared (GATED, never applied to production) to add
-- `p_record_import_alias boolean default true` to
-- public.resolve_import_guest_identity, so the two NON-import guest-creation
-- paths — the /group/players roster "add player" action and the Log-a-Game
-- manual-entry resolver — could skip the `player_import_aliases` insert.
-- `player_import_aliases.source_type` is constrained to import sources
-- ('game_log', 'screenshot_ocr'), so an alias row asserts "this name appeared
-- in an imported game log". For a roster-added or manually-entered guest that
-- assertion is false, and recording it would fabricate import provenance.
--
-- That need is real and still exists. This FILE, however, could not serve it,
-- for three independent reasons established by read-only investigation and
-- design scoping on 2026-07-22:
--
--   1. It ended with
--        grant execute on function public.resolve_import_guest_identity(
--          uuid, text, text, text, text, uuid, boolean, boolean
--        ) to authenticated;
--      Applying it would have RESTORED the `authenticated` EXECUTE that
--      production deliberately revoked as ledger version 20260722153233
--      (repo file 20260722153000_close_authenticated_guest_identity_oracle.sql),
--      reopening the private-guest-name confirmation oracle that revoke closed.
--
--   2. It did not repair blocker ID-READER-CLIENT. It kept the
--      `auth.uid()`-based gate and wrote `created_by_user_id` as
--      `(select auth.uid())`. `auth.uid()` is NULL under service_role, so the
--      call fails under the user-session client (authenticated revoked) AND
--      under the admin client (42501 from the body, then a NOT NULL violation
--      on private.player_private_identities.created_by_user_id).
--
--   3. It also DROPPED the deployed 7-argument signature. Dropping the
--      deployed function belongs to a separately gated CONTRACT phase, after
--      the replacement is live and verified — not to this expansion.
--
-- WHAT REPLACES IT
--
-- The still-needed capability — a non-import, source-unbound guest
-- reuse-or-create that records NO import evidence — now lives in a new,
-- distinctly-named, service_role-only function:
--
--   supabase/migrations/20260722160000_add_non_import_guest_identity_creator.sql
--   public.create_or_reuse_guest_identity(...)
--
-- That replacement additionally fixes the authorization break by taking an
-- explicit, server-verified `p_requesting_user_id` (the same trust model as the
-- four applied source-bound gateways in 20260722012658), and it never grants
-- `authenticated`. A distinct NAME was chosen over an overload deliberately:
-- this signature ends in five defaulted parameters, so an appended parameter is
-- forced to default, which makes the old 7-argument call ambiguous (42725).
--
-- The deployed 7-argument public.resolve_import_guest_identity is intentionally
-- LEFT IN PLACE by the replacement. Dropping it is the CONTRACT phase and
-- requires its own owner authorization, after the new reader is deployed and
-- verified.
--
-- Governance: this file stays on the branch, at its original version, as an
-- auditable record. It remains classified GATED_UNAPPLIED in
-- src/lib/db/migration-ledger-map.ts (it is not in the production ledger and
-- never will be), and its declared hazard class is now `neutral` because a
-- no-op changes no contract surface. Do not restore its previous body; the
-- capability moved, and the re-grant was a defect.
