import Image from 'next/image';
import { getSupabaseGameAssetUrl } from '@/lib/assets/supabase-game-assets';

// Corporation logos are self-hosted in the public tm-corporation-logos Supabase
// bucket under content-addressed keys. The exact production mapping is
// snapshotted here for UI surfaces that only have a corporation name and cannot
// perform another query.

/**
 * The art is a 2:1 banner carrying the corporation name as part of the image,
 * so it must render in a 2:1 box — fitting it into a square would halve its
 * height and letterbox it.
 */
export const CORPORATION_LOGO_ASPECT_RATIO = 2;

// Normalized corporation name -> logo filename in the bucket. Generated by
// scripts/catalog/upload-corporation-logos.ts; regenerate whenever the art or
// the corporation catalog changes. A name with no entry (e.g. an unmatched
// import value) renders nothing instead of a broken image.
const CORPORATION_LOGO_PATHS: Readonly<Record<string, string>> = {
  adhaihighorbitconstructions: 'corporation-logo-6468a4ddac250a72f5c2ba9ff4c8ca205b677fc8d5bd95a08f8a2a160f1e2c42.png',
  aerongenomics: 'corporation-logo-28b794e91673cbdf7e75dd846006365ea567501705882301f0fde2cd5031a8bf.png',
  aerotech: 'corporation-logo-059c6d428fb12f76b3e759ae25bb32daf29af717fd0aee905e8ff161edc7eb44.png',
  agricolainc: 'corporation-logo-9b5b13ff610220b0192cd48e06f43223cb7ec682590990dd04a135e2224774dd.png',
  ambient: 'corporation-logo-c0c96600638440670edbbab5ecb5952c73ec59768c41a5714101f9e53cbb1212.png',
  anubissecurities: 'corporation-logo-f04cf0fdb52e327acc2319961452b0f68fb41e16654dd7d5d61ee33c7ad86c0e.png',
  aphrodite: 'corporation-logo-019ccfa2f24ff6da8133477ff13684404e3f045fbfc53435dca3679c9ec567df.png',
  arboristcollective: 'corporation-logo-e5905f6c00505892c2aaf08c427c7d9355cd8461123f2e73b19b600bb2e27f5f.png',
  arcadiancommunities: 'corporation-logo-86daa7cccad56d6511a2d14109528c1814305b05cb0a01323a49b2d339444499.png',
  aridor: 'corporation-logo-4b3ddcf0b4afcda7661adc705217054c6fc3dc72525b3ae9b501587cdcb3ecda.png',
  aristarchus: 'corporation-logo-8c6957631c8376babb3eb6bed7709119024ef4eacb8c9c00e536c5cc2ddf9448.png',
  arklight: 'corporation-logo-acadebc44e9cb640bee33d48029d59e800353c4055c050e0fbcfdcdd08ed0209.png',
  astrodrill: 'corporation-logo-2edc4832f5f4af0de32ca5069ddb60ef1a25708d3a2cbc0a06b1921187ee224c.png',
  athena: 'corporation-logo-1f0f223f42b3136430f02a7f8e11feec8cbf555e2684dbb43e71aa1535f66070.png',
  aurorai: 'corporation-logo-8a9dc9a9c6596e2e6943471f48e7dd16388b0c0af68818008b7b24b61cacb1ab.png',
  beginnercorporation: 'corporation-logo-3da33511d3e6f6c25d6afbf0c84ecdfbd8c4a7e6d0be1930ab77fed99bc0dae4.png',
  bentenmaru: 'corporation-logo-635d155d9263743342646eac999bc5142d8554f9ecb09f9de27ac96803bd53c8.png',
  biosol: 'corporation-logo-5e7d994c039ac92232d3bb1eddf2e9e6f63788c4e9b0b4f7ab4afa9dc70515f2.png',
  celestic: 'corporation-logo-33d6cc84743b3b3cce08d6f0a2975d5027dce6b7f5ee9b898f459a2bacab8769.png',
  cheungshingmars: 'corporation-logo-0bbaf0d4bd4e0b35d27867b7cf62555438a74e8aa7b104401a400599b19874d4.png',
  chimera: 'corporation-logo-309fa4317a1062aca4f31bea371396d79a83d0440750228813c6c4af065bce4d.png',
  collegiumcopernicus: 'corporation-logo-b978be8d4e2c3f5af3852cebe84807ff5ba7b9c062e09eb0a5fede6a37c1714f.png',
  colonialone: 'corporation-logo-49bbdb69143bd909135e64123599aeb1d73f2bf0a5b31a4d40e00fb62f935270.png',
  credicor: 'corporation-logo-26dae5e60c5d32abe359764f767175dbe2b4b72368933d9114baed89c6963d74.png',
  crescentresearchassociation: 'corporation-logo-6bc1e95e9b7e4be623d486679f161fe7300e5875af2a4f48748f54c1923f4b64.png',
  curiosityii: 'corporation-logo-91a93b3057e31fda1a34a660629f7983977e5fc9dc69a3f5bb5b06ede97bab2e.png',
  demetronlabs: 'corporation-logo-cecde2ae174708128858451aca75c93eee5e0f53b8b3240736f138360ce602cf.png',
  ecoline: 'corporation-logo-45dd3c3c8b5117866c1081adb7b63cfda0af9e389bf769238790940db471e6c7.png',
  ecotec: 'corporation-logo-8d0a5dda1ab953ad06771a467284afca0ea7765868fd6b800bb2cdb5f284c6bb.png',
  eris: 'corporation-logo-b321a2bf6e6e7c6caf8d13ad5aeeadc9412c26233367989368faf917291f4d76.png',
  factorum: 'corporation-logo-09be2aa8b83d543638fef208e01b8dd3671094616e9783dc3af25018485a9839.png',
  fauxnews: 'corporation-logo-a298e8651f3666d56876eb4e4d658d6a6ac3daa795a3dc0f3b0ee1563edd85a9.png',
  gagarinmobilebase: 'corporation-logo-8907156c971fcdd12af971900a1dd39f3221f118ce9d435f600c6d418ac4b530.png',
  habitatmarte: 'corporation-logo-4a78572de79a0111107b6977dbc3bb7d9d497b3590713461d153b2571d5041a2.png',
  hadesphere: 'corporation-logo-9f2d2ed5f63f3de05a285b1a25b1f9df37c5a7d66b151f8602adde6064b3f898.png',
  hecatespeditions: 'corporation-logo-1b430d111dbf79aa20f446ac2957b7be188e3c9b5ddd2c36bc659693c4ae1444.png',
  helion: 'corporation-logo-915428b9598e14ce86ee502bb5584dcc26f422a6a6e3de38c426b19ee51c8430.png',
  henkeigenetics: 'corporation-logo-808ad9517f3f55f68b349afd8ec26c227b8c8743138436f1c2660ef889624054.png',
  hotsprings: 'corporation-logo-68eb382281031285255fa5438a613bf659d4c37f9bfb9720d7dceda3e2abd6e7.png',
  incite: 'corporation-logo-fad6ab4181fb9958bf9c200dd4800344d614345a7ac4d59a4b8343d23bec5ad7.png',
  interplanetarycinematics: 'corporation-logo-3ddcdfcab378610a82db007e05e9e49161eb5fa94b26be977a32c165ec9d63f5.png',
  intragensanctuaryheadquarters: 'corporation-logo-e0ab1f8336f3d8aa09ca2c7ab9b94a52a570a588da9adbe2dacd292e9854d912.png',
  inventrix: 'corporation-logo-92bdfec14d2e695b54ed68c58818691b8ec400a1ee677c076cafb8df214c4856.png',
  jensonboyleco: 'corporation-logo-9086ba2589511cae27962f6cbff9b98b6f205e57534daebb479ee3423b26e7c2.png',
  junkventures: 'corporation-logo-8beb4e4acc217d22c4d238c1b50990f9985ad1d7ce53897a2728ddcf213ec9b9.png',
  keplertec: 'corporation-logo-c433eba9dd70cdf26ea68b49975773099cba188ff30f0d468597b7bb3ce4591d.png',
  kingdomoftauraro: 'corporation-logo-693be22891e56132d98ebf8d41d033d7cfac8929531f05a0b234f0bb4bba75d4.png',
  kuipercooperative: 'corporation-logo-ee1dcc1a9f4b6daba418276fca2811cc1b3e5b07f8c916e5c1da331603db6dd3.png',
  labourunion: 'corporation-logo-f96d6b04badf590279f3b95731cd4630910e73273af3aacf94773062066619ef.png',
  lakefrontresorts: 'corporation-logo-1b0437bf51e32cbfa2c8a854ca384d1220bc963545697d6a19a3dabced7dd2dc.png',
  lunafirstincorporated: 'corporation-logo-bf46cf5ca4c7689c190ccef7cb4e5d86e22fd4a8796af485a0a2a5fc23a5c300.png',
  lunahyperloopcorporation: 'corporation-logo-81a48adf9d265f21e08f8e621219fb1fef925e21ac79b2119fd706ea688e4731.png',
  lunatradefederation: 'corporation-logo-ba65e51592744749e1e903691ba408273c4ac2acedae9731c4c9f25d5911db51.png',
  manutech: 'corporation-logo-956458dbe522783f9e60016f8f304ac123fc3bb27b32ea9277a84c094dbaedf9.png',
  maraboutshiritori: 'corporation-logo-f4c5e966d3187fdeb35a422810f713f0b0d4aa8106ecddc4696b09bec32af152.png',
  marscoalition: 'corporation-logo-7eb37ad13f24230b101bf55bf73884324243c6fc593d03fc3cd3bfe0e1efe76c.png',
  marsdirect: 'corporation-logo-712a06f4966347494bfe9d2586177ab869bf9ce916e5421520d9414b9cb7d1f6.png',
  marsmaths: 'corporation-logo-c2b895f59d306cf6cb49bf1e38027db2715d6c0dfd7df3e830f5a53b4b6ef77b.png',
  martianinsurancegroup: 'corporation-logo-0e8043bdef9be308f983a9fc2bf223817d2a94155325ab0f0411e00061738395.png',
  midas: 'corporation-logo-bedbfe80ddac83103a28f7293247b889a138b8cd1485af2e91b252b5b317c565.png',
  mindsetmars: 'corporation-logo-e65336a0fd260567bf61f68b9eb027212bc623bd6db52d4145f1149b20e9a458.png',
  miningguild: 'corporation-logo-ca4b3e277df45dc20e3b3c7a5522677e3b1c0f6706526edbe46d32f92dd7a0db.png',
  monsinsurance: 'corporation-logo-22a61bb8a4e4a4bbb9d5d17220bb370bfd77ccba8dcda7e4d20a455a3540d481.png',
  morningstarinc: 'corporation-logo-43fdaf1cc5d1aca3ef95ba53c9646d0b8427c94e2ee2e1f4503c2464f7f57eb7.png',
  nanotechindustries: 'corporation-logo-8ab579848b51aac3a6b1d43c60731ad711ce933c73faf1aaffcf3898fd5492b2.png',
  nirgalenterprises: 'corporation-logo-fdbe764beaa4937455b2ab0281dc3d32e664ae8e6811fff04315d524883a87a4.png',
  odyssey: 'corporation-logo-42725667017004ae120930f1df5fd7afe675028adad2e336d043d9c9183e4c7f.png',
  palladinshipping: 'corporation-logo-13b6b362c534a30fc87d2d48ca96ceb97ddccc9afbe58f1f453787e3255d26ae.png',
  pharmacyunion: 'corporation-logo-4427e3ab4eab511e3f7de943a772ea19a5c402b7bfce24bad8bbd5b6b7966b0b.png',
  philares: 'corporation-logo-535921edb9c29d737ad0c228cdf9ce9b26a4a6ffdda1b60fddd06a7107465b5c.png',
  phobolog: 'corporation-logo-d11b66e3ef25be07da666e0fed3b88ade9de821b66554a8b573e457de133be66.png',
  playwrights: 'corporation-logo-0c7b9902e3eb75ab04a2c18813a0f6af18134c39ee51659e82ca79fa0ebf288f.png',
  pointluna: 'corporation-logo-6cd8a2f042bd2032106761e1ad4b3a7eab711db5051d4aafe585b623e495b5ea.png',
  polaris: 'corporation-logo-71ecac6588e9d0dec6b6cb19659e83b523e88c9fd45c1ab66fe99abc96895f4d.png',
  poldertechdutch: 'corporation-logo-9349293abb815db47997c2b2d9add27d76dbf33e92b47112de98240a39a2a795.png',
  polyphemos: 'corporation-logo-99e80f12b387e0d8e17733d6638aac45bf77128bc16be70990a53de80cf42077.png',
  poseidon: 'corporation-logo-be86fca65be54a27a669f65efa7aaac13b101ebe1f7e96ec3923d44cd07e8b0a.png',
  pristar: 'corporation-logo-633b0717c264eeaf759ec48017f9d0f4438ffe0c11ad7a49314de2ae4d0030c9.png',
  project10: 'corporation-logo-5a15c00ec7cabeb6aac4d22d2232c6fb7f4dbfeaaaf74d961aa36f381e965e19.png',
  projectworkshop: 'corporation-logo-5f4b00090ec0f7ad61d9fc5e15e5fbf1f0d0ac5ab9545ef7d97804068e9ef307.png',
  recyclon: 'corporation-logo-de1d520e0081af16a52f381a71c06d93cec6c8b2531db49bf1569a003d9ac101.png',
  ringcom: 'corporation-logo-5df2de9f6dc670e9cd96aa7b9155893d47385e7840ca054de3fed8e6529b67e6.png',
  robinhaulings: 'corporation-logo-f068c9838a88d4d697ef0dd2387249660ff3160657c2749e73d489b798d87d06.png',
  robinsonindustries: 'corporation-logo-ad057e8e63c853e9cbcdb37f1fdb182d535e875e739aae01bc04a078ab36e31d.png',
  sagittafrontierservices: 'corporation-logo-a67962e4b256ab5b7b61d48729bc11a73ac1574c7613685308020d61f4eba2f8.png',
  saturnsystems: 'corporation-logo-0c6448c8ba885167eb5fbc5a5bf8571bc06c866a42dc5903a1fb11acaf2d081b.png',
  secretsantasociety: 'corporation-logo-8eb8bf13c08e42c69278151999305c377fd6f5f9a9bad91c13543df74095e303.png',
  septemtribus: 'corporation-logo-5f932156e0ca65a4d870d57b5e2611e09f6f69120a5f4eb1fa885c9bc6e6fced.png',
  solbank: 'corporation-logo-5b5b2eef6f78d972cd25ad10777c39ac90aa8350518beaec0b4d0401537bc9fe.png',
  soylentseedlingsystems: 'corporation-logo-0939ac935e970891cc1b8011c1a0fc558d9459997852b0ea7250dae101baf4e0.png',
  spaceways: 'corporation-logo-31660e687c81f08e20fb93e0e12c95baaaad4e974d1095d66a645be50f7f968b.png',
  spire: 'corporation-logo-9557a48ea85ae3f3ff2b12dc8f3f9e82d190229cd61dfb5f9c17b10843b4ad5e.png',
  splice: 'corporation-logo-621c6986159029194b65cd930fab8adcea0cb80e114da4ed8b2d9e87f6c2e5a0.png',
  steelaris: 'corporation-logo-6f00f6e0265e545c57d52f487ec3b94215aefc8fb2427de253c6cb144ee4281a.png',
  stormcraftincorporated: 'corporation-logo-51b53c198db121281ec4750b6409517e0c2eb02b64448a204644e3ffc76b2e4d.png',
  tempestconsultancy: 'corporation-logo-99fc63f257a4db9fa0fbb2c70386144eda949c44241f3386bf73d5f72e611b18.png',
  tempestinc: 'corporation-logo-452d7d42905503b514a08212eb7498b2db2340bd7d835671e2fb1f2563e1cd3e.png',
  teractor: 'corporation-logo-95759a13955cae45b6a90bfac0257cdf627c0ffbb936bb01cf7c5a6d69a679d4.png',
  terralabsresearch: 'corporation-logo-c75b68a27d6abef0cea8c7307aeb823fd1ebe65cd07cf90b55f5c8b38196fbec.png',
  tharsisrepublic: 'corporation-logo-de486b6850942a3370e18e10c69e3399fb98a5271c71e646aab6ab25fda74a02.png',
  thearchaicfoundationinstitute: 'corporation-logo-b6067436cb53107fbcfd51807461ef653a116d58404e2e256a89ae125f97388f.png',
  thedarksideofthemoonsyndicate: 'corporation-logo-34689bea6eb559e2e43326043d2a36357bcf0bc3888621fb5de642c48f4b1003.png',
  thegrandlunacapitalgroup: 'corporation-logo-6e1b4a4e3f377ab43a0339ea46b7954a600eb50d78aaf5a928bf73d63deb45d9.png',
  thorgate: 'corporation-logo-15d31385ef67986dc946131668b596e4b5d8f4f7be4ff9139f8a84ac9f7804cf.png',
  tychomagnetics: 'corporation-logo-af6bf42f32e02953c675285e6cff7f4238fba199b2bec9462ebbd60cb2a693f2.png',
  unitednationsmarsinitiative: 'corporation-logo-9c57524bbe5031abd7eb0913d1108f3c09db5bc859ce96637ab4cd7f19b9c192.png',
  unitednationsmissionone: 'corporation-logo-b305ed06a2c0646842f2b4bf824d148af19707776ff64319ee842ebeab95c34a.png',
  utopiainvest: 'corporation-logo-d5ac4ea0015bada43d58a9a88e05965fc4e12d77586572cbe21fe73c72aae1bc.png',
  valleytrust: 'corporation-logo-8f335e222bf84b52292e81683c4e21303d1e19f67d24a2ef34b06caf947730dd.png',
  viron: 'corporation-logo-0e5cb2c1741bdeca255954542a5ec05b2b853004224be458ae1ba8a2776222c6.png',
  vitor: 'corporation-logo-04fd9bd5573412737f1a7e489ea3dc85be98a2b49db159477e057f623cf87044.png',
  voltagon: 'corporation-logo-80d7f5f06bd50c10c352137ed12f4e83b236a0c9c3464cf8fd70bcec86cb1c5e.png',
};

export function normalizeCorporationName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '');
}

export function hasCorporationLogo(name: string): boolean {
  return normalizeCorporationName(name) in CORPORATION_LOGO_PATHS;
}

export function getCorporationLogoUrl(name: string): string | null {
  const path = CORPORATION_LOGO_PATHS[normalizeCorporationName(name)];
  return path ? getSupabaseGameAssetUrl('tm-corporation-logos', path) : null;
}

export function CorporationLogo({
  className,
  name,
  size = 24,
}: {
  className?: string;
  name: string;
  /**
   * Rendered height in px. Width is derived as
   * `size * CORPORATION_LOGO_ASPECT_RATIO` so the banner art is never squashed.
   */
  size?: number;
}) {
  const path = CORPORATION_LOGO_PATHS[normalizeCorporationName(name)];

  if (!path) {
    return null;
  }

  return (
    <Image
      alt={`${name} logo`}
      className={`object-contain ${className ?? ''}`}
      height={size}
      src={getSupabaseGameAssetUrl('tm-corporation-logos', path)}
      unoptimized
      width={size * CORPORATION_LOGO_ASPECT_RATIO}
    />
  );
}
